### ISSUE TITLE
Buchempfehlung

### ISSUE THREAD

**Issue by sjargin** [a-g-van-hamel-foundation/codecs#7]
Referred from: Geneva, Bibliothèque de Genève.
Sehr geehrte Damen und Herren, 
Darf ich die Anschaffung des neu erschienenen Buches empfehlen: Jargin SV. The Conflict in Ukraine: Psychopathology and Social Aspects. New York: Nova Science Publishers, 2023. ISBN: 979-8-89113-020-3. 
https://novapublishers.com/shop/the-conflict-in-ukraine-psychopathology-and-social-aspects/ 
Hier ist ein Artikel (Hektoen International 2023), der als Zusammenfassung des Buches angesehen werden kann:
https://hekint.org/2023/05/30/psychopathological-aspects-of-the-war-in-ukraine/
Hochachtungsvoll, 
Sergei Jargin

**Comment by D-Groenewegen** [comment]
Thanks for your suggestion, but I don't think this is particularly relevant to Celtic studies.
