### ISSUE TITLE
Outdated link/linkrot - Jan Deloof Woordenboek

### ISSUE THREAD

**Issue by PrivacyDragon** [a-g-van-hamel-foundation/codecs#9]
Referred from: Jan Deloof Woordenboek BZH-NL-BZH.
The Jan Deloof dictionary is no longer available online under the previously used brezhoneg.org.uk website. Said domain name has expired. I contacted Kevin Donelly about this, who maintains it, and learned that the dictionary is now to be found at https://kevindonnelly.org.uk/deloof

**Comment by D-Groenewegen** [comment]
Thanks, I have updated the link. And many thanks to @donnekgit for maintaining the site.
